### PR TITLE
Be less restrictive about dependencies versions and solve elixir 1.4 warnings

### PR DESCRIPTION
**Pull request by Nagasaki45**
Some minor changes to `mix.exs` that I found necessary.

### CODE REVIEW

**Comment by jordan0day** [comment]
D'oh, sorry, for some reason I wasn't getting any github notifications for this project. Thanks for the 1.4 fixes, but I prefer a little more caution on the versioning.

**Comment by Nagasaki45** [comment]
Hi @jordan0day, thanks for your response.

I'm relatively new to elixir. In a project I'm working on I already have `jose`, `httpoison`, and `poison` as dependencies, but with different versions than those specified by `big_query`. I proposed this commit as it solved the issue for me and I couldn't see any downside, but maybe I'm wrong.
I would like to improve this PR, maybe by completely droping the 1st commit, please let me know what would you prefer.

**Comment by jordan0day** [comment]
Mix does have a decent workaround for your type of scenario, in your mix.exs where you're using newer versions of those libraries, you can specify `override: true` to basically tell mix "This is the version I really want to use!" Ex:

`{:jose, "1.8.1", override: true}`

If you want to drop the first commit for now, I'll test the library against the latest versions of those dependencies when I get a chance and maybe bump them then. Thanks again!

**Comment by Nagasaki45** [comment]
I dropped the versioning changes commit from the PR. Thank you very much for the tip! I learned something new :-)

**Comment by gVolop** [comment]
https://github.com/companykitchen/big_query/pull/7#issuecomment-284239167

**Pull request merged**
